export function masterLinks() {
  return {
    "core": {
      "GCP": "https://console.cloud.google.com/home/dashboard?project=poc-tier1&authuser=0",
      "Dynect": "https://manage.dynect.net/login/",
      "Okta": "https://westfieldlabs.okta.com/app/UserHome",
      "Fastly": "https://manage.fastly.com/",
      "ZenDesk": "https://westfieldlabs.zendesk.com/hc/en-us",
      "One Market Api": "https://api.one.market/v1/",
      "Labs Kong Links": "https://ops-docs.polarisdev.io/labs/kong/urls/",
    },
    "github": {
      "WRSINC": "https://github.com/wrsinc",
      "Personal": "https://github.com/gabrie30",
      "Westfield Org": "https://github.com/westfield",
      "Operations Org": "https://github.com/westfieldoperations",
      "Sandbox Public": "https://github.com/wf-sandbox-public",
      "Sandbox Private": "https://github.com/wf-sandbox-private",
      "Github Status Page": "https://status.github.com/messages",
    },
    "miscLinks": {
      "localhost:4000": "localhost:4000",
      "localhost:3000": "localhost:3000",
      "Time Converter": "https://www.worldtimebuddy.com/?pl=1&lid=5391959,100&h=5391959",
      "K8 proxy UI": "http://127.0.0.1:8001/ui",
      "repl.it": "https://repl.it/languages/ruby",
      "regex101": "https://regex101.com/",
      "Safari Online": "http://my.safaribooksonline.com/",
      "Gliffy": "https://www.gliffy.com/go/html5/launch",
      "Elixir Playground": "http://elixirplayground.com/",
      "Golang Playground": "https://play.golang.org/",
      "White Noise": "https://www.youtube.com/watch?v=wzjWIxXBs_s",
    },
    "monitoring": {
      "Splunk Prod": "https://logging.one.market",
      "Splunk Preprod": "https://logging.preprod.one.market",
      "All Splunk Links": "https://ops-docs.polarisdev.io/ops/splunk/overview/#splunk-master-links",
      "Pager Duty": "https://onemarket.pagerduty.com/incidents",
      "Status Page": "https://manage.statuspage.io/login",
      "New Relic": "https://rpm.newrelic.com/accounts/10589/applications",
      "Nagios": "https://monitoring.one.market/",
      "SonarQube": "https://sonarqube.one.market/#",
    },
    "opsServices": {
      "New Jenkins": "https://test.one.market/",
      "Security Jenkins": "https://security-test.one.market/",
      "Legacy Jenkins": "https://legacy-ci.westfield.io",
      "Create": "https://create.one.market/",
      "Deliver": "https://deliver.one.market",
      "Ops Docs": "https://ops-docs.polarisdev.io",
      "Polaris Docs": "https://polaris-docs.polarisdev.io",
      "Support Docs": "https://support-docs.polarisdev.io",
      "Governance Docs": "https://governance-docs.polarisdev.io",
    },
    "westfield": {
      "Stock Price": "https://www.marketindex.com.au/asx/omn",
      "Intranet": "https://sites.google.com/onemarketnetwork.com/intranet/employee-tools?authuser=0",
      "Polaris Swagger": "https://retailerswagger.onemarketnetwork.com/",
      "Payroll Calendar": "https://westfieldus.app.box.com/s/901xrnmgtopeajkkflnsngk7lxyw1gve",
      "Holiday Calendar": "https://westfieldus.app.box.com/s/35h4ytwfsovi0e23lamwrqowa9euuq7s",
    },
    "navbar": {
      "leftButton": { "jira": "https://jira.westfieldlabs.com/secure/Dashboard.jspa" },
      "rightButton": { "gmail": "https://www.gmail.com" }
    },
  }
}
