export function masterLinks() {
  return {
    "core": {
      "GCP": "https://console.cloud.google.com/home/dashboard?project=poc-tier1&authuser=0",
      "AWS": "https://westfieldlabs.okta.com/home/amazon_aws/0oa180m5dmtrIrcDq1d8/272",
      "Dynect": "https://manage.dynect.net/login/",
      "Okta": "https://westfieldlabs.okta.com/app/UserHome",
      // "Westfield Splunk": "https://westfieldlabs.splunkcloud.com",
      "Fastly": "https://manage.fastly.com/",
      "ZenDesk": "https://westfieldlabs.zendesk.com/hc/en-us",
      "Labs Infra Links": "https://ops-docs.polarisdev.io/Labs/URLs/devops/#",
    },
    "github": {
      "WRSINC": "https://github.com/wrsinc",
      "Westfield Org": "https://github.com/westfield",
      "Operations Org": "https://github.com/westfieldoperations",
      "Sandbox Public": "https://github.com/wf-sandbox-public",
      "Sandbox Private": "https://github.com/wf-sandbox-private",
      "Github Status Page": "https://status.github.com/graphs/past_day",
    },
    "miscLinks": {
      "localhost:4000": "localhost:4000",
      "localhost:3000": "localhost:3000",
      "K8 proxy UI": "http://127.0.0.1:8001/ui",
      "repl.it": "https://repl.it/languages/ruby",
      "regex101": "https://regex101.com/",
      "Safari Online": "http://my.safaribooksonline.com/",
      "Gliffy": "https://www.gliffy.com/go/html5/launch",
      "Elixir Playground": "http://elixirplayground.com/",
      "Golang Playground": "https://play.golang.org/",
      "White Noise": "https://www.youtube.com/watch?v=wzjWIxXBs_s",
    },
    "monitoring": {
      "Splunk Prod": "https://logging.one.market",
      "Splunk Preprod": "https://logging.preprod.one.market",
      // "Poc Logs": "https://logs.poc.wrsops.net",
      // "Integration Logs": "https://logs.integration.wrsops.net",
      // "Staging Logs": "https://logs.staging.wrsops.net",
      // "Sandbox Logs": "https://logs.sandbox.wrsops.net",
      // "Performance Logs": "https://logs.performance.wrsops.net",
      // "Production Logs": "https://logs.production.wrsops.net",
      "Pager Duty": "https://westfieldlabs.pagerduty.com/incidents",
      "Status Page": "https://manage.statuspage.io/login",
      "New Relic": "https://rpm.newrelic.com/accounts/10589/applications",
      "Nagios": "https://monitoring.one.market/",
    },
    "opsServices": {
      "New Jenkins": "https://test.one.market/",
      "Old Jenkins": "https://test.westfield.io/",
      "Create": "https://create.one.market/",
      "Deliver": "https://deliver.one.market",
      // "Create (uat)":"https://create.uat.westfield.io",
      // "Jenkins (uat)":"https://test.uat.westfield.io",
      // "Deliver (uat)":"https://deliver.uat.westfield.io",
      // "Pager Duty Service":"http://pagerduty-service.herokuapp.com/pagerduty",
      // "Redirect Service (uat)":"https://redis-redirect-service.uat.wflops.net/",
      // "Harmonizer (vpn)":"https://harmonizer.internal.wflops.net",
      "Ops Docs": "https://ops-docs.polarisdev.io",
      "Polaris Docs": "https://polaris-docs.polarisdev.io",
      "Support Docs": "https://support-docs.polarisdev.io",
      // "Platform Docs": "https://platform-docs.polarisdev.io",
      "Governance Docs": "https://governance-docs.polarisdev.io"

    },
    "westfield": {
      "Intranet": "https://sites.google.com/onemarketnetwork.com/intranet/employee-tools?authuser=0",
      "Polaris Swagger": "https://retailerswagger.onemarketnetwork.com/",
      "Service Portal": "https://westfield.service-now.com/sp",
      "Workday": "https://sso.westfield.com/adfs/ls/idpinitiatedSignon.aspx?loginToRp=http://www.workday.com&done=http%3A%2F%2Fwww.myworkday.com%2Fwestfield%2Fd%2Finst%2F779%2453414%2Frel-task%2F2997%244086.htmld",
      "Okta - Westfield Corp": "https://westfield.okta.com/app/UserHome",
      "Okta Preview": "https://westfieldlabs.oktapreview.com/app/UserHome",
      "Payroll Calendar": "https://westfieldus.app.box.com/s/901xrnmgtopeajkkflnsngk7lxyw1gve",
      "Holiday Calendar": "https://westfieldus.app.box.com/s/35h4ytwfsovi0e23lamwrqowa9euuq7s"
    },
    "navbar": {
      "leftButton": { "jira": "https://jira.westfieldlabs.com/secure/Dashboard.jspa" },
      "rightButton": { "gmail": "https://www.gmail.com" }
    },
  }
}
