export function masterLinks() {
  return {
    "cloud": {
      "AWS Console": "https://console.aws.amazon.com/",
      "GCP Console": "https://console.cloud.google.com/",
      "Azure Portal": "https://portal.azure.com/",
      "Terraform Cloud": "https://app.terraform.io/",
      "Cloudflare": "https://dash.cloudflare.com/",
      "DigitalOcean": "https://cloud.digitalocean.com/",
      "Vercel": "https://vercel.com/dashboard",
      "Netlify": "https://app.netlify.com/",
    },
    "devtools": {
      "GitHub": "https://github.com/",
      "GitLab": "https://gitlab.com/",
      "Stack Overflow": "https://stackoverflow.com/",
      "Docker Hub": "https://hub.docker.com/",
      "npm": "https://www.npmjs.com/",
      "PyPI": "https://pypi.org/",
      "Crates.io": "https://crates.io/",
      "GitHub Status": "https://www.githubstatus.com/",
    },
    "monitoring": {
      "Grafana Cloud": "https://grafana.com/",
      "Datadog": "https://app.datadoghq.com/",
      "PagerDuty": "https://app.pagerduty.com/",
      "Sentry": "https://sentry.io/",
      "New Relic": "https://one.newrelic.com/",
      "Statuspage": "https://www.atlassian.com/software/statuspage",
      "Uptime Robot": "https://uptimerobot.com/",
    },
    "docs": {
      "MDN Web Docs": "https://developer.mozilla.org/",
      "DevDocs": "https://devdocs.io/",
      "React Docs": "https://react.dev/",
      "TypeScript Docs": "https://www.typescriptlang.org/docs/",
      "Node.js Docs": "https://nodejs.org/en/docs/",
      "Kubernetes Docs": "https://kubernetes.io/docs/",
      "Terraform Docs": "https://developer.hashicorp.com/terraform/docs",
      "Go Docs": "https://go.dev/doc/",
    },
    "productivity": {
      "Gmail": "https://mail.google.com/",
      "Google Calendar": "https://calendar.google.com/",
      "Google Drive": "https://drive.google.com/",
      "Notion": "https://www.notion.so/",
      "Slack": "https://slack.com/",
      "Linear": "https://linear.app/",
      "Figma": "https://www.figma.com/",
    },
    "utilities": {
      "regex101": "https://regex101.com/",
      "JSON Formatter": "https://jsonformatter.org/",
      "Excalidraw": "https://excalidraw.com/",
      "Can I Use": "https://caniuse.com/",
      "Hacker News": "https://news.ycombinator.com/",
      "Time Converter": "https://www.worldtimebuddy.com/",
      "localhost:3000": "http://localhost:3000",
    },
    "navbar": {
      "leftButton": { "GitHub": "https://github.com/" },
      "rightButton": { "Gmail": "https://mail.google.com/" }
    },
    "awsServices": [
      "ec2",
      "s3",
      "lambda",
      "rds",
      "ecs",
      "eks",
      "cloudformation",
      "iam",
      "cloudwatch",
      "route53",
      "dynamodb",
      "sqs",
      "sns",
      "elasticache",
    ],
    "popularRepos": [
      "facebook/react",
      "vercel/next.js",
      "microsoft/vscode",
      "golang/go",
      "kubernetes/kubernetes",
      "hashicorp/terraform",
      "grafana/grafana",
      "prometheus/prometheus",
      "docker/compose",
      "tailwindlabs/tailwindcss",
    ]
  }
}
